// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewzsiiclccdhszlbqzex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3enNpaWNsY2NkaHN6bGJxemV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDc1NzMsImV4cCI6MjA1OTY4MzU3M30.6vMbsVs0N4h_hmlB-kOMRfaEfkbrffQGYSAhc6XA1uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);